### ISSUE TITLE
If there's no role, it doesn't work

### ISSUE THREAD

**Issue by geazersb** [mahtoid/DiscordChatExporterPy#1]
![image](https://user-images.githubusercontent.com/72651083/95654585-319a4a00-0b01-11eb-8dde-ed0853baff13.png)

**Comment by mahtoid** [comment]
Hello,

Thank you for reporting this issue.

I've ran a few tests and detected the issue happened when mentioning deleted/removed roles. I've just pushed an update fixing this issue, and also fixing it for mentioning deleted channels. 

Please update your version and let me know if this has resolved the problem for you.

Thank you again!
