### ISSUE TITLE
Incorrect formatting with user mentions within embed descriptions.

### ISSUE THREAD

**Issue by Brian-van-Rheenen** [mahtoid/DiscordChatExporterPy#10]
When there's a user mention inside an embed, the formatting will be all over the place. This seems to happen only if it's within the description and not a field. I have linked 2 screenshots below.
This issue is relevant to #9, but has another problem besides the emojis.

Formatting with the exporter:
![Capture](https://user-images.githubusercontent.com/27146982/118987740-d37bf200-b980-11eb-8bfa-ecb1ada4d13f.PNG)
Formatting on Discord:
![Capture](https://user-images.githubusercontent.com/27146982/118987629-bd6e3180-b980-11eb-95a6-8142551f89ea.PNG)

**Comment by mahtoid** [comment]
Thank you for your report, I've managed to replicate the issues and have pushed a fix to the code. I'll push a version to pypi a little later today.

If you get any other issues, feel free to open up another issue - or alternatively join the Discord: discord.gg/jeAdPaC

**Comment by Brian-van-Rheenen** [comment]
I noticed that the first emoji is not quite placed correctly when there's a user mention next to it.
Formatting with the exporter:
![Capture](https://user-images.githubusercontent.com/27146982/119557399-7036f900-bda0-11eb-8cce-9d5a82c582c6.PNG)

Formatting on Discord:
![Capture](https://user-images.githubusercontent.com/27146982/119557580-a83e3c00-bda0-11eb-8c82-320201cea800.PNG)
