### ISSUE TITLE
Custom AttachmentHandler Not being Used

### ISSUE THREAD

**Issue by 1337Syntax** [mahtoid/DiscordChatExporterPy#107]
### DiscordChatExporterPy Version

2.7.1

### Discord Version

discord.py 2.3.2

### Bug Description

I am attempting to use a custom `AttachmentHandler` in my `export()`, however it does not seem to be using it:

```py
class AttachmentHandler(chat_exporter.AttachmentHandler):
    """Custom Attachment Handler"""

    def __init__(self, session: aiohttp.ClientSession, *args, **kwargs) -> None:
        self._session = session

    async def process_asset(self, attachment: discord.Attachment) -> discord.Attachment:
        . . . # Upload Logic
        attachment.url = new_url
        print(attachment.url) # Test to See if Function is Called
        return attachment

. . .

transcript = await chat_exporter.export(
    channel=channel,
    before=now,
    guild=channel.guild,
    bot=self.bot,
    military_time=True,
    fancy_times=True,
    attachment_handler=AttachmentHandler(self.bot.session),
)
```

The generated transcript shows the Discord proxy links, not my custom ones (and nothing seems to get printed either from `process_asset`) . The transcript also seems to be missing other assets like the colour of embeds and misalignment in buttons.

### Additional Information

Mis-Alignment of the Emoji & Label in Button:
![image](https://github.com/mahtoid/DiscordChatExporterPy/assets/70772334/a10674f6-76d1-4084-8f99-f06e8b09c7d4)

**Comment by doluk** [comment]
Chat exporter uses the attribute proxy_url instead of url. Based on your code, you only modify the url attribute. Therefore the proxy_url will still be the discord CDN ones. (Looks like I forgot to explicitly mention that in the docs, sry)

The missing print in the console is something different, I can't help with that without seeing the code.

You always welcomed to open a pr for improving the css :D

**Comment by 1337Syntax** [comment]
After rebuilding the packages again, it now runs the custom attachment handler, and yes editing `proxy_url` works!
