### ISSUE TITLE
Error creating a transcript.

### ISSUE THREAD

**Issue by Friendliness** [mahtoid/DiscordChatExporterPy#109]
### DiscordChatExporterPy Version

2.7.1

### Discord Version

2.3.2

### Bug Description

This occurred when creating a transcript using a local filehost handler.
I'm unsure what the channel was that had the error, I'll try to investigate when I get the time.

### Bug Traceback

![image](https://github.com/mahtoid/DiscordChatExporterPy/assets/62225953/6b55e63e-f625-4e88-932a-cabb8bf57284)

**Comment by mahtoid** [comment]
This will be fixed in the next version, coming soon:tm:

**Comment by Friendliness** [comment]
Awesome, thanks! :)

**Comment by mahtoid** [comment]
This should now be solved, please run `pip install --upgrade chat-exporter` to get the latest version.

If you find any issues, please open up an issue - thank you and sorry for the wait! 💜

**Comment by Friendliness** [comment]
> This should now be solved, please run `pip install --upgrade chat-exporter` to get the latest version.
> 
> If you find any issues, please open up an issue - thank you and sorry for the wait! 💜

Thanks a ton, I appreciate it! No problem at all :)
