### ISSUE TITLE
Incorrect formatting with role mentions in message content with an embed.

### ISSUE THREAD

**Issue by Brian-van-Rheenen** [mahtoid/DiscordChatExporterPy#11]
This is very similair to my previous #10 issue, but this time it's inside the content of the message and not the embed itself. Here are 2 screenshots. (It's all 1 message sent by the bot: `ctx.channel.send(content=mentions, embed=embed)`)
I'm not sure if this is specifically tied to role mentions or that's also user mentions, I have not tested that since my bot only allows role mentions.

Formatting with the exporter:
![Capture](https://user-images.githubusercontent.com/27146982/119556557-77113c00-bd9f-11eb-87e6-cfd07853350a.PNG)

Formatting on Discord:
![Capture](https://user-images.githubusercontent.com/27146982/119556597-84c6c180-bd9f-11eb-8d60-b44ff2e0f880.PNG)

**Comment by mahtoid** [comment]
I'll give this a look soon, there is a hotfix coming soon for another issue - which may potentially solve this issue you're facing.

**Comment by Brian-van-Rheenen** [comment]
Alright, I also noticed something else that was relevant to the previous issue. Just something small though. I couldn't re-open the issue.
https://github.com/mahtoid/DiscordChatExporterPy/issues/10

**Comment by mahtoid** [comment]
What's the other issue you have noticed?

**Comment by Brian-van-Rheenen** [comment]
Copy pasted:

I noticed that the first emoji is not quite placed correctly when there's a user mention next to it.
Formatting with the exporter:
![Capture](https://user-images.githubusercontent.com/27146982/119557399-7036f900-bda0-11eb-8cce-9d5a82c582c6.PNG)

Formatting on Discord:
![Capture](https://user-images.githubusercontent.com/27146982/119557580-a83e3c00-bda0-11eb-8c82-320201cea800.PNG)

**Comment by mahtoid** [comment]
I'm pretty sure all of the issues stated here are solved in the most lastest commit. Would there be any chance you could clone the repository and test or pass me a link to your guild where I can run the check before I push things to release.

Discord: mahtoid#3787

**Comment by mahtoid** [comment]
This has all been solved and released in the latest version (1.4.1). 
As DM'd, the spaces actually exist in your embed - Discord kind of does an `.lstrip()` on display; however they're still there.

Appreciate the bug reports yet again though! Keep them coming 💜
