### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by tobfd** [mahtoid/DiscordChatExporterPy#113]
### DiscordChatExporterPy Version

2.7.1

### Discord Version

2.5.1.dev96+gbf401165

### Bug Description

since pycord version 2.6 interaction is outdated see https://pycord--2409.org.readthedocs.build/en/2409/api/models.html#discord.Message.interaction and therefore i get many errors in my console see picture.
![336194753-e1b35c98-ccb1-492d-b231-0c881c91f7c4](https://github.com/mahtoid/DiscordChatExporterPy/assets/77446267/ddb22212-cc17-4200-927f-b46a41dcf8fe)

### Bug Traceback

C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Scripts\python.exe C:\Users\tobia\PycharmProjects\tobfd_bot\main.py 
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\discord\ext\bridge\bot.py:41: DeprecationWarning: Option is deprecated since version 2.5, consider using BridgeOption instead. See https://github.com/Pycord-Development/pycord/pull/2417 for more information.
  from .core import (
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\discord\client.py:219: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop() if loop is None else loop
[COG] Loaded 19 cogs
[INFO] Bot is online with EzCord 0.6.4
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:308: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if self.message.reference != "" or self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:319: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  ("REFERENCE", self.message.reference if self.message.reference else self.message.interaction,
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:188: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not message.interaction and (message.embeds or message.attachments):
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:308: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if self.message.reference != "" or self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:319: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  ("REFERENCE", self.message.reference if self.message.reference else self.message.interaction,
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:188: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not message.interaction and (message.embeds or message.attachments):
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:188: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not message.interaction and (message.embeds or message.attachments):
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:188: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not message.interaction and (message.embeds or message.attachments):
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:308: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if self.message.reference != "" or self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:319: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  ("REFERENCE", self.message.reference if self.message.reference else self.message.interaction,
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:188: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not message.interaction and (message.embeds or message.attachments):
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:213: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  if not self.message.interaction:
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\chat_exporter\construct\message.py:214: DeprecationWarning: interaction is deprecated since version 2.6, consider using interaction_metadata instead. See https://discord.com/developers/docs/change-log#userinstallable-apps-preview for more information.
  self.message.interaction = ""
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\aiosqlite\core.py:115: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  result = function()
C:\Users\tobia\PycharmProjects\tobfd_bot\.venv\Lib\site-packages\aiosqlite\core.py:115: DeprecationWarning: The default timestamp converter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  result = function()

**Comment by doluk** [comment]
This isn't a bug nor an error strictly speaking. It is just a deprecation message. You can turn it those of with something like [this](https://stackoverflow.com/questions/879173/how-to-ignore-deprecation-warnings-in-python) until we added support for that :)

**Comment by Ewxun** [comment]
discord.py v2.4 has fully deprecated the `message.interaction` method. It also currently uses the new `message.interaction_metadata` method. Hope you can implement an update on this soon!

**Comment by mahtoid** [comment]
@Ewxun we plan to run a hotfix soon solving this issue, sorry for the delay.

**Comment by MarikIsGod2** [comment]
Would be amazing if this could be fixed soon. It seems like the Module is unusable with the newest discord py version at the moment. 

This is the error im getting. The transcript only contains the following. 

/usr/local/lib/python3.12/site-packages/chat_exporter/construct/message.py:104: DeprecationWarning: interaction is deprecated, use interaction_metadata instead.
2024-06-29T10:51:47.974970768Z   await self.build_interaction()
2024-06-29T10:51:47.975116149Z Traceback (most recent call last):
2024-06-29T10:51:47.975344637Z   File "/usr/local/lib/python3.12/site-packages/chat_exporter/construct/transcript.py", line 175, in export
2024-06-29T10:51:47.975359769Z     return await super().build_transcript()
2024-06-29T10:51:47.975361457Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-29T10:51:47.975362499Z   File "/usr/local/lib/python3.12/site-packages/chat_exporter/construct/transcript.py", line 59, in build_transcript
2024-06-29T10:51:47.975363625Z     message_html, meta_data = await gather_messages(
2024-06-29T10:51:47.975364583Z                               ^^^^^^^^^^^^^^^^^^^^^^
2024-06-29T10:51:47.975365539Z   File "/usr/local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 465, in gather_messages
2024-06-29T10:51:47.975366595Z     content_html, meta_data = await MessageConstruct(
2024-06-29T10:51:47.975367798Z                               ^^^^^^^^^^^^^^^^^^^^^^^
2024-06-29T10:51:47.975368793Z   File "/usr/local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 98, in construct_message
2024-06-29T10:51:47.975369844Z     await self.build_message()
2024-06-29T10:51:47.975370845Z   File "/usr/local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 104, in build_message
2024-06-29T10:51:47.975373819Z     await self.build_interaction()
2024-06-29T10:51:47.975374786Z   File "/usr/local/lib/python3.12/site-packages/chat_exporter/construct/message.py", line 214, in build_interaction
2024-06-29T10:51:47.975375843Z     self.message.interaction = ""
2024-06-29T10:51:47.975376876Z     ^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-29T10:51:47.975377896Z AttributeError: property 'interaction' of 'Message' object has no setter
2024-06-29T10:51:47.975378919Z Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy


Transcript generated: 
Whoops! Something went wrong...

**Comment by mahtoid** [comment]
Solution is in `2.8.0` - will be releasing soon (hopefully today).

**Comment by mahtoid** [comment]
This is solved now, please run `pip install --upgrade chat-exporter` to get the latest version.

If you find any issues, please open up an issue - thank you and sorry for the wait! 💜
