### ISSUE TITLE
Export contents to json

### ISSUE THREAD

**Issue by neilstottler** [mahtoid/DiscordChatExporterPy#116]
### Feature Description

It's a pretty simple concept that I'm asking for. Instead of exporting it to html it would be nice if I could get it in a json format so I can parse through the data myself and extract only certain bits. Or if we can export from a specific user (a bot in this case).

**Comment by mahtoid** [comment]
This isn't going to be something coming to `chat-exporter`. 

I do plan to do a rewrite at some point in the future, making it more JS generation as opposed to all ran inside Python on the fly - which would take in a "JSON" object. However, this will be more or less the response of `channel.history()` without any editing. 

If you was wanting a JSON output, then again just grab the channel history and you have your JSON.
