### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by ERFFFFF** [mahtoid/DiscordChatExporterPy#121]
### Feature Description

Hello,

Would it be possible to add in the API a timezone to the exported chanel ?, i only saw the UTC date, unfortunatelly, i would like to set it in my native language (French).

Something like that :
transcript = await chat_exporter.export(interaction.channel, "Europe/Paris")

Thank you,

**Comment by doluk** [comment]
@ERFFFFF this is already implemented with the `tz_info` parameter of `chat_exporter.export()` and `chat_exporter.raw_export()`. It supports the timezones `datetime.datetime.now()` supports. It will default to `'UTC'`.

**Comment by ERFFFFF** [comment]
My bad, didn't see it. Thank you so much for your help !

**Comment by ERFFFFF** [comment]
My bad, didn't see it. Thank you so much for your help !
