### ISSUE TITLE
interaction_metadata

### ISSUE THREAD

**Issue by kosmo6666** [mahtoid/DiscordChatExporterPy#122]
### DiscordChatExporterPy Version

newest

### Discord Version

newest

### Bug Description

I get this error interaction_metadata
When I try to log a transcript

### Bug Traceback

NameError: name 'interaction_metadata' is not defined

**Comment by doluk** [comment]
@kosmo6666 what discord api wrapper are you using? What chat-exporter version are you using? please provide more details and minimum example to reproduce this issue

**Comment by mahtoid** [comment]
Closing due to inactive.
