### ISSUE TITLE
To much advertisement...

### ISSUE THREAD

**Issue by CodingEnte** [mahtoid/DiscordChatExporterPy#125]
### DiscordChatExporterPy Version

2.7.1

### Discord Version

Pycord 2.6.1

### Bug Description

**Just to much advertisement. I would've been fine with just having it somewhere but a bit less, but that's to much, like dude.**
![image](https://github.com/user-attachments/assets/98c60245-ba3e-402f-b3ff-e927bdc8c432)

Can I pay to get it removed?

**Comment by mahtoid** [comment]
Cheers
