### ISSUE TITLE
Wrong avatar shown for replied-to messages

### ISSUE THREAD

**Issue by oneup40** [mahtoid/DiscordChatExporterPy#19]
First of all, awesome work with this project so far. I was glad to see somebody had made a Python version of this which makes it way easier to integrate into a Python-based bot than the original .NET one.

One very minor thing I noticed though is that the wrong avatar is shown for the author of a replied-to message. Instead of showing the author of the original message, it seems to show the author of the new message twice:

**Expected** (as seen in Discord web client):

![image](https://user-images.githubusercontent.com/7097256/131950832-75d80287-99a3-4304-b8ac-6c72aed2bed5.png)

**Actual** (as seen in exported transcript):

![image](https://user-images.githubusercontent.com/7097256/131951081-dec57ee9-bf06-4270-8b73-5fd12eac7b25.png)

**Comment by mahtoid** [comment]
Thank you for reporting this issue, I'll check in to this tomorrow and confirm.

**Comment by mahtoid** [comment]
I can confirm this is an issue, thank you for catching this.

I've pushed a solve to Github (which you can update if you cloned the repository). I'll be pushing a new version to pypi in the next couple of days. 

Thank you! 💜
