### ISSUE TITLE
Embed not showing correctly

### ISSUE THREAD

**Issue by AZalshehri7** [mahtoid/DiscordChatExporterPy#2]
Hey there, 

I found two issues with the embeds in general. First one is the embed field always shows as `inline=True` and the other one is that markdown links inside the embed show as row text. Here is two photos showing the difference.

![html](https://user-images.githubusercontent.com/48307757/99464698-c3d80e00-2949-11eb-8dd3-1bc8dddcd188.png)
![discord](https://user-images.githubusercontent.com/48307757/99464770-ed913500-2949-11eb-8f39-d70fee0dbc10.png)

**Comment by mahtoid** [comment]
I've also noticed the additional issue of the embed assigning a `footer_icon` even when there isn't one in the HTML document. 

I'll get on to fixing this as soon as I can (I'll update this PR when it's updated to give you a nudge), thank you! 💜

**Comment by mahtoid** [comment]
@AZalshehri7 This should now be fixed! Make sure you update your module

Thank you once again, and remember to open up another issue (or join the Discord) if you find any more problems 🥇💜
