### ISSUE TITLE
author_icon returning _EmptyEmbed (potential fork issue)

### ISSUE THREAD

**Issue by PandaDEVpy** [mahtoid/DiscordChatExporterPy#31]
![image](https://user-images.githubusercontent.com/70103896/156773632-19e9b61f-0d56-475a-8e91-1ebb90fe2dd9.png)

**Comment by Hichoow** [comment]
Downgrade to version 1.7.3

pip install chat-exporter==1.7.3

**Comment by mahtoid** [comment]
Hello @PandaDEVpy

I'm struggling to replicate this issue - could you please let me know what version of `discord.py` (or fork) you are using please.

**Comment by mahtoid** [comment]
I'm closing this ticket due to inactivity, feel free to reopen if you still have an issue.
