### ISSUE TITLE
Message Components in wrong order

### ISSUE THREAD

**Issue by Kapppa** [mahtoid/DiscordChatExporterPy#44]
When exporting a channel with Message Components they will be in the wrong order. 

Example:
[Discord](https://i.jimbo.dev/7giv1ddw.png)
[Export](https://i.jimbo.dev/sqvx15b7.png)

As you can see on Discord the buttons are below the embed while in the Export the buttons are above the Embed.

**Comment by mahtoid** [comment]
Hey @Kapppa - thank you for the report.

This should already be resolved within the `dev` branch which I should be releasing ~~1 month ago~~ this weekend coming. I'll keep this issue open until I can double check and confirm that it is resolved in the upcoming version. 

Thank you once again

**Comment by mahtoid** [comment]
I can confirm this is definitely solved in `dev` which will be releasing real soon.

Thank you for the bug report, keep an eye out for the release! 🎉 💜
