### ISSUE TITLE
Member object has no attribute display_icon

### ISSUE THREAD

**Issue by nmarotte** [mahtoid/DiscordChatExporterPy#46]
### DiscordChatExporterPy Version

2.2

### Discord Version

pycord 2.0.0rc1

### Bug Description

Calling chat_exporter.export on a channel where there is a bot with no profile picture set results in a traceback. Maybe this libraray doesn't work with pycord but discord.py instead ?

Also : the guild does not have a profile picture either, that might be it 

### Bug Traceback

`Traceback (most recent call last):
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\transcript.py", line 74, in export
    return await super().build_transcript()
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\transcript.py", line 39, in build_transcript
    message_html = await Message(
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\message.py", line 297, in gather
    message_html += await MessageConstruct(
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\message.py", line 69, in construct_message
    await self.build_message()
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\message.py", line 77, in build_message
    await self.build_message_template()
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\message.py", line 173, in build_message_template
    await self.generate_message_divider()
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\message.py", line 210, in generate_message_divider
    ("USER_ICON", await self._gather_user_icon(self.message.author), PARSE_MODE_NONE),
  File "C:\Users\natha\PycharmProjects\TalyaBot\venv\AppData\Local\Programs\Python\Python\lib\site-packages\chat_exporter\construct\message.py", line 256, in _gather_user_icon
    if member and member.display_icon:
AttributeError: 'Member' object has no attribute 'display_icon'
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy`

**Comment by mahtoid** [comment]
`.display_icon` is to display the members role icon. 

Within `pycord` they don't have a member attribute to do this. Instead I will have to chase down the `.top_role` then gather the `.icon` from that. 

Although this is definitely a bug, I have no urgency to solve this and will take a look at this at the end of the week. As a solution for now, you may want to downgrade to 2.1. 

You can downgrade by using: `pip install discord.py==2.1.1`

---

Although of course it is your personal choice, I'd always recommend using `discord.py 2.0a` over `pycord`. It has a much higher level of code quality and is much more sane. Additionally, I'm always going to develop towards `discord.py` and at a later 
date backport fixes for the other forks.

**Comment by nmarotte** [comment]
Thanks for the reply, from what I found on pycord we can also use the display_avatar attribute that will return the guild specific icon, or the user icon, or the default avatar in that order

Unfortunately I can't work with discord.py since I am using recent functionalities of discord such as threads and discord.py was not updated for that at that time

**Comment by mahtoid** [comment]
The `.display_icon` gathers the image for the icon next to the users name, not the avatar of the user.

For example:
![image](https://user-images.githubusercontent.com/56257224/172671245-afa72d26-ba8a-4f25-88fc-9cfe49d2ed86.png)

Next to `Cap` you see the Wumpus icon, next to `Nelly` you see the art _thing_ and next to `Wumpus` you see a smiley face.

---

I understand that. With Danny archiving dpy, then bringing it back to life made people change direction and it is just as annoying to bring it back. I'd always say it is worth it though - reading some of the PRs being merged in to Pycord have been quite... shocking to say the least (although I can't bash it too much, the code quality within this repo isn't top-tier either - but two negatives don't make a positive in this case, haha.).

**Comment by Kapppa** [comment]
Same issue with Nextcord. I can do a fix later today

**Comment by nmarotte** [comment]
No I did mean display_avatar which is a property of Member in pycord, but it's probably different for discord.py

**Comment by mahtoid** [comment]
@nmarotte There seems to be some misunderstanding.

The `AttributeError: 'Member' object has no attribute 'display_icon'` refers to `.display_icon` which gathers the member icon (as shown in the screenshot above). This is nothing to do with an avatar.

`.display_avatar` in discord py, pycord and nextcord are the exact same thing (referring to getting the avatar, and defaulting to `None` if there isn't one - as you explained). But this is something else, the icons.

This will be solved once Kapppa has adjusted their PR.

**Comment by nmarotte** [comment]
Oh yes my bad I thought the traceback was about the profile picture nevermind 😅

**Comment by mahtoid** [comment]
This has now been resolved in the latest version. 
Please update to the latest version `2.2.1` - you can do this by doing `pip install --upgrade chat-exporter`

Thank you once again for your report and to @Kapppa for the PR. 
If you find any other issues, feel free to open up another issue on Github - or alternatively, you can [join the Discord](https://discord.gg/mq3hYaJSfa).

💜
