### ISSUE TITLE
Pin Add messages do not export as expected

### ISSUE THREAD

**Issue by Septikai** [mahtoid/DiscordChatExporterPy#48]
### DiscordChatExporterPy Version

2.2.1

### Discord Version

Discord.py 2.0.0a4318+g823d650e (Most recent commit at time of writing)

### Bug Description

When creating a transcript with `export()` or `quick_export()` (I haven't tested with  `raw_export()`), any messages to show a pin being added will be shown as an empty message from the user pinning the message, replying to the message they pinned, instead of a message stating "USER pinned **a message** to this channel. See all **pinned messages**."

### Bug Traceback

No console output.

### Additional Information

![image](https://user-images.githubusercontent.com/52349324/174674049-41f80dbd-da9f-4c82-b237-1799a44d4f2f.png)
![image](https://user-images.githubusercontent.com/52349324/174674096-83b17e16-b2a9-43b2-aad6-84916fd7682b.png)

**Comment by Septikai** [comment]
From what I can find, in dpy, the MessageType of pins being added is an enum, `MessageType.pins_add`, rather than a string as chat-exporter seems to expect [here](https://github.com/mahtoid/DiscordChatExporterPy/blob/65160e2f91df2dc88ac1c6788cc99d1eccf81868/chat_exporter/construct/message.py#L64).
![image](https://user-images.githubusercontent.com/52349324/174675270-e4e4a3b0-7f9a-4e66-89c2-635c300458d3.png)
![image](https://user-images.githubusercontent.com/52349324/174675495-8e4db31b-82de-429e-bbb5-9c25e6debef1.png)

**Comment by mahtoid** [comment]
Thank you for the report.

This issue was brought up within the Discord server ~a week ago. I have the solve locally which I can push up to the Repo, although it will probably sit on a `dev` branch until `2.3` is ready.  

I'll keep this issue open until the branch is up.

**Comment by mahtoid** [comment]
I forgot to drop a message here. This has been added to the `development` branch.

You can clone the repository in to your project then checkout that branch if you wish to use it locally until it'll be released. 

_Please note, I have also updated a bunch of CSS and re-added HTML escaping, so there may be some issues. If you find anything, let me know._

**Comment by Septikai** [comment]
Thanks, will do.
