### ISSUE TITLE
Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

### ISSUE THREAD

**Issue by BossMan32143** [mahtoid/DiscordChatExporterPy#50]
### DiscordChatExporterPy Version

v2.2.2

### Discord Version

py-cord v2.0.0rc1

### Bug Description

I'm using this to log transcripts for my ticket bot and when I try closing already created tickets I get the error message "Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.". I just tested with a few new tickets and its working fine with them but with older tickets it gives that error

### Bug Traceback

Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.

### Additional Information

![Screenshot_1](https://user-images.githubusercontent.com/72342998/180874561-7cd0e5a5-04a3-40d9-8121-2bac4c51098b.png)

**Comment by mahtoid** [comment]
Hey @BossMan32143 - by any chance did you delete the transcript file from Discord?

**Comment by BossMan32143** [comment]
> 

Yea it does delete the HTML file because the ticket channel gets deleted, I did not realize that would cause a problem. Is there a way to select what channel the HTML file gets sent into? if so how would I go around doing it
