### ISSUE TITLE
TypeError: demojize() got an unexpected keyword argument 'use_aliases' (1.7.3)

### ISSUE THREAD

**Issue by gaRt3n** [mahtoid/DiscordChatExporterPy#57]
### DiscordChatExporterPy Version

1.7.3

### Discord Version

1.7.3

### Bug Description

0|FoxCodeBot  | Traceback (most recent call last):
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 44, in export
0|FoxCodeBot  |     return (await Transcript.export(channel, limit, set_timezone)).html
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 129, in export
0|FoxCodeBot  |     transcript = await Transcript(
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 161, in build_transcript
0|FoxCodeBot  |     message_html += await Message(m, previous_message, self.timezone_string).build_input()
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 237, in build_input
0|FoxCodeBot  |     await self.build_message()
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 249, in build_message
0|FoxCodeBot  |     await self.build_content()
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/chat_exporter.py", line 356, in build_content
0|FoxCodeBot  |     self.message.content = await fill_out(self.guild, message_content, [
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/build_html.py", line 28, in fill_out
0|FoxCodeBot  |     v = await ParseMarkdown(v).standard_message_flow()
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/parse_markdown.py", line 13, in standard_message_flow
0|FoxCodeBot  |     await self.parse_emoji()
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/parse_markdown.py", line 62, in parse_emoji
0|FoxCodeBot  |     self.content = await convert_emoji([word for word in self.content])
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/emoji_convert.py", line 88, in convert_emoji
0|FoxCodeBot  |     x.append(await convert(ch))
0|FoxCodeBot  |   File "/home/corebot/.local/lib/python3.9/site-packages/chat_exporter/emoji_convert.py", line 74, in convert
0|FoxCodeBot  |     shortcode = emoji.demojize(char, use_aliases=True)
0|FoxCodeBot  | TypeError: demojize() got an unexpected keyword argument 'use_aliases'
0|FoxCodeBot  | Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by mahtoid** [comment]
Hello @gaRt3n - thank you for reporting this issue.

This issue is solved in later versions of `chat-exporter`, however because you are using `discord.py==1.7.3` it'll be a little problematic.

To solve this issue for now on your current version, you can downgrade the `emoji` package to `1.7.0` - you can do so by running: `pip install emoji==1.7.0`.

I will however keep this issue open while I try and solve this problem for `1.7.3`

**Comment by mahtoid** [comment]
Discord py got updated to `2.0` - you can update both dpy and chat-exporter; closing this issue out.
