### ISSUE TITLE
Multiple Error

### ISSUE THREAD

**Issue by api-was-taken** [mahtoid/DiscordChatExporterPy#64]
### DiscordChatExporterPy Version

2.2.2 + 1.7.3

### Discord Version

1.7.3

### Bug Description

So i was told to downgrade from chat-export 2.2.2 to 1.7.3 To get rid of this error `AttributeError: 'NoneType' object has no attribute 'html'`

But when i downgrade to v1.7.3 I get this Error: `TypeError: demojize() got an unexpected keyword argument 'use_aliases'`

Please Help!

**Comment by mahtoid** [comment]
You can either downgrade `emoji` to `1.7.0` (`pip install emoji==1.7.0`) or you can remove the `use_aliases` from `emoji_convert.py` in your package files (`L74`)

Should look like so: <https://github.com/mahtoid/DiscordChatExporterPy/blob/master/chat_exporter/ext/emoji_convert.py#L74>

**Comment by api-was-taken** [comment]
> You can either downgrade `emoji` to `1.7.0` (`pip install emoji==1.7.0`) or you can remove the `use_aliases` from `emoji_convert.py` in your package files (`L74`)
> 
> Should look like so: https://github.com/mahtoid/DiscordChatExporterPy/blob/master/chat_exporter/ext/emoji_convert.py#L74

How would i do this?

**Comment by api-was-taken** [comment]
Ive tried downgrading emoji and i get error

**Comment by api-was-taken** [comment]
nvm i got it!
