### ISSUE TITLE
Got this error today, worked just fine not so long ago

### ISSUE THREAD

**Issue by siren15** [mahtoid/DiscordChatExporterPy#7]
![image](https://user-images.githubusercontent.com/65129243/109842957-e2d58400-7c4a-11eb-9bc5-b7bc05b90440.png)
I'm using it in a cog, if that helps in some way.

**Comment by mahtoid** [comment]
Hello @siren15 - Thank you for your ticket.

I'm not able to reproduce this issue. How are you calling the function?

**Comment by mahtoid** [comment]
Closing ticket as unable to reproduce and no response. 

If this issue still consists for you, please join the Discord (link at the bottom of the README), and I'll be happy to help.

💜
