### ISSUE TITLE
pins_add not message_type

### ISSUE THREAD

**Issue by Agent-Lemm1ngs** [mahtoid/DiscordChatExporterPy#73]
### DiscordChatExporterPy Version

2.4.1

### Discord Version

nextcord ver 2.3.2

### Bug Description

I was trying to generate a transcript, when I hit this error. The exact same code works perfectly on replit, but not on my host when I tried.

### Bug Traceback

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/chat_exporter/construct/transcript.py", line 153, in export
    return await super().build_transcript()
  File "/home/container/.local/lib/python3.10/site-packages/chat_exporter/construct/transcript.py", line 51, in build_transcript
    message_html, meta_data = await gather_messages(
  File "/home/container/.local/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 353, in gather_messages
    content_html, meta_data = await MessageConstruct(
  File "/home/container/.local/lib/python3.10/site-packages/chat_exporter/construct/message.py", line 72, in construct_message
    if "pins_add" in self.message.type:
TypeError: argument of type 'MessageType' is not iterable
Please send a screenshot of the above error to https://www.github.com/mahtoid/DiscordChatExporterPy

**Comment by mahtoid** [comment]
Hello @Agent-Lemm1ngs - sorry for the delay!

I have just solved this issue and pushed it to the `development` branch ready for release when I can get around to it.

If you would like to solve this issue now, feel free to edit the `chat-exporter` code in your local venv. The solve is pretty simple and can be found [here](https://github.com/mahtoid/DiscordChatExporterPy/commit/9c2c5b9a0e55d85b403ec9e894d865ec62860984).

The file to edit within `chat-exporter` is at `/chat_exporter/construct/message.py` at `L78` and `L80`.

I will leave this issue open until I release the next version. Hopefully at this weekend coming, sorry once again for the delay!

**Comment by mahtoid** [comment]
This should now be resolved on the latest release. Please run `pip install --upgrade chat-exporter` to get the latest version.

Hopefully this solves the issue you were facing, however - if there is still an issue, or you find any others - then please open another Github Issue, or better yet [join the Discord](https://discord.gg/mq3hYaJSfa) 

Thank you for reporting the issue, and sorry once again for the delays! 💜
