### ISSUE TITLE
Bug with check interaction in message

### ISSUE THREAD

**Issue by IBEATERI** [mahtoid/DiscordChatExporterPy#80]
### DiscordChatExporterPy Version

2.5.3

### Discord Version

2.2.0

### Bug Description

I used chat_exporter.export(), then sent it to specific channel and deleted previous channel ( where I use export() ). Previous channel has embeds with buttons (interaction), but when export() tryed to check interaction in message it cause error.

### Bug Traceback

https://imgur.com/a/kkESoA3

**Comment by mahtoid** [comment]
@IBEATERI Sorry for the delay. 

You are using `discord.py==2.2.0`? This error should not be happening, this was introduced in `2.0`.
Could you check to make sure you have no other discord forks installed?
