### ISSUE TITLE
Limit by timestamp

### ISSUE THREAD

**Issue by addi00000** [mahtoid/DiscordChatExporterPy#81]
### Feature Description

Allow `.export()` to limit by timestamp. If latest timestamp is set to `1672531200` it will fetch all messages more recently made than `Sun Jan 01 2023 00:00:00 GMT+0000`

Suggested implementation
```py
.export(
    channel=channel,
    within=1672531200
)
```

**Comment by mahtoid** [comment]
Hey @addi00000,

That's a nice idea. I will add it to the list and hopefully can squeeze it in to the next version, seems like a quick win.

**Comment by mahtoid** [comment]
This has been added to the `to-do` list to come in within the next version. 
Feel free to keep up to date with development on the Discord.
