### ISSUE TITLE
Emojis in embeds aren't supported

### ISSUE THREAD

**Issue by Cats3153** [mahtoid/DiscordChatExporterPy#9]
They still render as <:emoji:id>, however, when outside of an embed, it renders correctly.

**Comment by mahtoid** [comment]
Thank you for your report, I've managed to replicate the issue and have pushed a fix to the code. I'll push a version to pypi a little later today. 

If you get any other issues, feel free to open up another issue - or alternatively join the Discord: discord.gg/jeAdPaC
