### ISSUE TITLE
Saving Images

### ISSUE THREAD

**Issue by YesYesTheDev** [mahtoid/DiscordChatExporterPy#95]
### Feature Description

Add a feature where the transcript will save all of the images locally so when the new discord cdn update comes it won't mess with images not showing.

**Comment by mahtoid** [comment]
@YesYesTheDev This has been solved in the next version which should be releasing soon. Keep an eye out for it

**Comment by YesYesTheDev** [comment]
Is their any update on when this will be releasing?
